### ISSUE TITLE
typeorm migration 관련 코드 수정

### ISSUE THREAD

**Issue by hdmun** [hdmun/poker-tournament-time-table#30]
`scr/database/migrations/1664241347477-tournament-blind.ts` 리버트 할 경우 아래와 같은 에러 메세지가 발생하고 있다.

```
query: SELECT VERSION() AS `version`
query: SELECT * FROM `INFORMATION_SCHEMA`.`COLUMNS` WHERE `TABLE_SCHEMA` = 'poker_tournament_dev' AND `TABLE_NAME` = 'migrations'
query: SELECT * FROM `poker_tournament_dev`.`migrations` `migrations` ORDER BY `id` DESC
1 migrations are already loaded in the database.
tournamentBlind1664241347477 is the last executed migration. It was executed on Tue Sep 27 2022 10:15:47 GMT+0900 (대한민국 표준시).
Now reverting it...
query: START TRANSACTION
query: ALTER TABLE `tournament` CHANGE `pause_time` `pause_time` datetime NULL DEFAULT 'NULL'
query failed: ALTER TABLE `tournament` CHANGE `pause_time` `pause_time` datetime NULL DEFAULT 'NULL'
error: Error: Invalid default value for 'pause_time'
    at Packet.asError (E:\poker-tournament-time-table\poker-time-table-backend\node_modules\mysql2\lib\packets\packet.js:728:17)
    at Query.execute (E:\poker-tournament-time-table\poker-time-table-backend\node_modules\mysql2\lib\commands\command.js:29:26)
    at PoolConnection.handlePacket (E:\poker-tournament-time-table\poker-time-table-backend\node_modules\mysql2\lib\connection.js:456:32)
    at PacketParser.onPacket (E:\poker-tournament-time-table\poker-time-table-backend\node_modules\mysql2\lib\connection.js:85:12)
    at PacketParser.executeStart (E:\poker-tournament-time-table\poker-time-table-backend\node_modules\mysql2\lib\packet_parser.js:75:16)
    at Socket.<anonymous> (E:\poker-tournament-time-table\poker-time-table-backend\node_modules\mysql2\lib\connection.js:92:25)
    at Socket.emit (node:events:527:28)
    at Socket.emit (node:domain:475:12)
    at addChunk (node:internal/streams/readable:315:12)
    at readableAddChunk (node:internal/streams/readable:289:9) {
  code: 'ER_INVALID_DEFAULT',
  errno: 1067,
  sqlState: '42000',
  sqlMessage: "Invalid default value for 'pause_time'",
  sql: "ALTER TABLE `tournament` CHANGE `pause_time` `pause_time` datetime NULL DEFAULT 'NULL'"
}
query: ROLLBACK
```

**Comment by hdmun** [comment]
`DEFAULT 'NULL'` 
위와 같은 쿼리가 문제로 발견

`DEFAULT NULL` 으로 수정하자
